spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/product_service?authSource=admin
      host: localhost
      port: 27017
      database: order_query_service
  application:
    name: order-query-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-query-group
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonSerializer
          json:
            trusted:
              packages: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8084